### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by Smith-Steve** [Smith-Steve/c0321-code-solutions#126]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a flight.
## 📐 Functionality

- User will be able to create a flight.
- User will be able to pull in an existing e-mail chain.
- User will be able to remove contacts from a flight if they change their mind.

> ##### A description of how the application will work from the perspective of the user.
A user will be able to name and provide limited information about the flight. 

I plan on creating a flight creation page, so that a user of this application will be able to create a flight. Creating a flight will consist of the following activities - the actual creation of a flight, attaching an e-mail chain to a flight, adding contacts to a flight, removing contacts from a flight.

There will have to be some sort of viewing interface which will allow the user to view which users they have added to the flight, and buttons will have to be attached 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature_2](https://user-images.githubusercontent.com/51938797/119423847-22939100-bcb9-11eb-9323-471d33f4534a.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...
- [ ] Create client calls with database for flights.

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client
- [ ] flights table should have an id column to identify the flight.
- [ ] flights table should have a name column to identify the name of the flight. Additionally, this field may be needed later for searching.
- [ ] flights table should have a scriptsId column within it that should be a foreign key from the scripts table. This will allow the database to identify which script has been attached to a flight.

### ⚡ Client

- [ ] Create a component to set up a flight.
- [ ] Update component to display the contacts that have been entered into the flight.

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
